<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use App\Models\CountryModel;


class CountrySeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	CountryModel::create ([ 'code' =>  'AF', 'name' => 'Afghanistan']);
        CountryModel::create ([ 'code' =>  'AL', 'name' => 'Albania']);
        CountryModel::create ([ 'code' =>  'DZ', 'name' => 'Algeria']);
        CountryModel::create ([ 'code' =>  'DS', 'name' => 'American Samoa']);
        CountryModel::create ([ 'code' =>  'AD', 'name' => 'Andorra']);
        CountryModel::create ([ 'code' =>  'AO', 'name' => 'Angola']);
        CountryModel::create ([ 'code' =>  'AI', 'name' => 'Anguilla']);
        CountryModel::create ([ 'code' =>  'AQ', 'name' => 'Antarctica']);
        CountryModel::create ([ 'code' =>  'AG', 'name' => 'Antigua and Barbuda']);
        CountryModel::create ([ 'code' =>  'AR', 'name' => 'Argentina']);
        CountryModel::create ([ 'code' =>  'AM', 'name' => 'Armenia']);
        CountryModel::create ([ 'code' =>  'AW', 'name' => 'Aruba']);
        CountryModel::create ([ 'code' =>  'AU', 'name' => 'Australia']);
        CountryModel::create ([ 'code' =>  'AT', 'name' => 'Austria']);
        CountryModel::create ([ 'code' =>  'AZ', 'name' => 'Azerbaijan']);
        CountryModel::create ([ 'code' =>  'BS', 'name' => 'Bahamas']);
        CountryModel::create ([ 'code' =>  'BH', 'name' => 'Bahrain']);
        CountryModel::create ([ 'code' =>  'BD', 'name' => 'Bangladesh']);
        CountryModel::create ([ 'code' =>  'BB', 'name' => 'Barbados']);
        CountryModel::create ([ 'code' =>  'BY', 'name' => 'Belarus']);
        CountryModel::create ([ 'code' =>  'BE', 'name' => 'Belgium']);
        CountryModel::create ([ 'code' =>  'BZ', 'name' => 'Belize']);
        CountryModel::create ([ 'code' =>  'BJ', 'name' => 'Benin']);
        CountryModel::create ([ 'code' =>  'BM', 'name' => 'Bermuda']);
        CountryModel::create ([ 'code' =>  'BT', 'name' => 'Bhutan']);
        CountryModel::create ([ 'code' =>  'BO', 'name' => 'Bolivia']);
        CountryModel::create ([ 'code' =>  'BA', 'name' => 'Bosnia and Herzegovina']);
        CountryModel::create ([ 'code' =>  'BW', 'name' => 'Botswana']);
        CountryModel::create ([ 'code' =>  'BV', 'name' => 'Bouvet Island']);
        CountryModel::create ([ 'code' =>  'BR', 'name' => 'Brazil']);
        CountryModel::create ([ 'code' =>  'IO', 'name' => 'British Indian Ocean Territory']);
        CountryModel::create ([ 'code' =>  'BN', 'name' => 'Brunei Darussalam']);
        CountryModel::create ([ 'code' =>  'BG', 'name' => 'Bulgaria']);
        CountryModel::create ([ 'code' =>  'BF', 'name' => 'Burkina Faso']);
        CountryModel::create ([ 'code' =>  'BI', 'name' => 'Burundi']);
        CountryModel::create ([ 'code' =>  'KH', 'name' => 'Cambodia']);
        CountryModel::create ([ 'code' =>  'CM', 'name' => 'Cameroon']);
        CountryModel::create ([ 'code' =>  'CA', 'name' => 'Canada']);
        CountryModel::create ([ 'code' =>  'CV', 'name' => 'Cape Verde']);
        CountryModel::create ([ 'code' =>  'KY', 'name' => 'Cayman Islands']);
        CountryModel::create ([ 'code' =>  'CF', 'name' => 'Central African Republic']);
        CountryModel::create ([ 'code' =>  'TD', 'name' => 'Chad']);
        CountryModel::create ([ 'code' =>  'CL', 'name' => 'Chile']);
        CountryModel::create ([ 'code' =>  'CN', 'name' => 'China']);
        CountryModel::create ([ 'code' =>  'CX', 'name' => 'Christmas Island']);
        CountryModel::create ([ 'code' =>  'CC', 'name' => 'Cocos (Keeling) Islands']);
        CountryModel::create ([ 'code' =>  'CO', 'name' => 'Colombia']);
        CountryModel::create ([ 'code' =>  'KM', 'name' => 'Comoros']);
        CountryModel::create ([ 'code' =>  'CG', 'name' => 'Congo']);
        CountryModel::create ([ 'code' =>  'CK', 'name' => 'Cook Islands']);
        CountryModel::create ([ 'code' =>  'CR', 'name' => 'Costa Rica']);
        CountryModel::create ([ 'code' =>  'HR', 'name' => 'Croatia (Hrvatska)']);
        CountryModel::create ([ 'code' =>  'CU', 'name' => 'Cuba']);
        CountryModel::create ([ 'code' =>  'CY', 'name' => 'Cyprus']);
        CountryModel::create ([ 'code' =>  'CZ', 'name' => 'Czech Republic']);
        CountryModel::create ([ 'code' =>  'DK', 'name' => 'Denmark']);
        CountryModel::create ([ 'code' =>  'DJ', 'name' => 'Djibouti']);
        CountryModel::create ([ 'code' =>  'DM', 'name' => 'Dominica']);
        CountryModel::create ([ 'code' =>  'DO', 'name' => 'Dominican Republic']);
        CountryModel::create ([ 'code' =>  'TP', 'name' => 'East Timor']);
        CountryModel::create ([ 'code' =>  'EC', 'name' => 'Ecuador']);
        CountryModel::create ([ 'code' =>  'EG', 'name' => 'Egypt']);
        CountryModel::create ([ 'code' =>  'SV', 'name' => 'El Salvador']);
        CountryModel::create ([ 'code' =>  'GQ', 'name' => 'Equatorial Guinea']);
        CountryModel::create ([ 'code' =>  'ER', 'name' => 'Eritrea']);
        CountryModel::create ([ 'code' =>  'EE', 'name' => 'Estonia']);
        CountryModel::create ([ 'code' =>  'ET', 'name' => 'Ethiopia']);
        CountryModel::create ([ 'code' =>  'FK', 'name' => 'Falkland Islands (Malvinas)']);
        CountryModel::create ([ 'code' =>  'FO', 'name' => 'Faroe Islands']);
        CountryModel::create ([ 'code' =>  'FJ', 'name' => 'Fiji']);
        CountryModel::create ([ 'code' =>  'FI', 'name' => 'Finland']);
        CountryModel::create ([ 'code' =>  'FR', 'name' => 'France']);
        CountryModel::create ([ 'code' =>  'FX', 'name' => 'France, Metropolitan']);
        CountryModel::create ([ 'code' =>  'GF', 'name' => 'French Guiana']);
        CountryModel::create ([ 'code' =>  'PF', 'name' => 'French Polynesia']);
        CountryModel::create ([ 'code' =>  'TF', 'name' => 'French Southern Territories']);
        CountryModel::create ([ 'code' =>  'GA', 'name' => 'Gabon']);
        CountryModel::create ([ 'code' =>  'GM', 'name' => 'Gambia']);
        CountryModel::create ([ 'code' =>  'GE', 'name' => 'Georgia']);
        CountryModel::create ([ 'code' =>  'DE', 'name' => 'Germany']);
        CountryModel::create ([ 'code' =>  'GH', 'name' => 'Ghana']);
        CountryModel::create ([ 'code' =>  'GI', 'name' => 'Gibraltar']);
        CountryModel::create ([ 'code' =>  'GK', 'name' => 'Guernsey']);
        CountryModel::create ([ 'code' =>  'GR', 'name' => 'Greece']);
        CountryModel::create ([ 'code' =>  'GL', 'name' => 'Greenland']);
        CountryModel::create ([ 'code' =>  'GD', 'name' => 'Grenada']);
        CountryModel::create ([ 'code' =>  'GP', 'name' => 'Guadeloupe']);
        CountryModel::create ([ 'code' =>  'GU', 'name' => 'Guam']);
        CountryModel::create ([ 'code' =>  'GT', 'name' => 'Guatemala']);
        CountryModel::create ([ 'code' =>  'GN', 'name' => 'Guinea']);
        CountryModel::create ([ 'code' =>  'GW', 'name' => 'Guinea-Bissau']);
        CountryModel::create ([ 'code' =>  'GY', 'name' => 'Guyana']);
        CountryModel::create ([ 'code' =>  'HT', 'name' => 'Haiti']);
        CountryModel::create ([ 'code' =>  'HM', 'name' => 'Heard and Mc Donald Islands']);
        CountryModel::create ([ 'code' =>  'HN', 'name' => 'Honduras']);
        CountryModel::create ([ 'code' =>  'HK', 'name' => 'Hong Kong']);
        CountryModel::create ([ 'code' =>  'HU', 'name' => 'Hungary']);
        CountryModel::create ([ 'code' =>  'IS', 'name' => 'Iceland']);
        CountryModel::create ([ 'code' =>  'IN', 'name' => 'India']);
        CountryModel::create ([ 'code' =>  'IM', 'name' => 'Isle of Man']);
        CountryModel::create ([ 'code' =>  'ID', 'name' => 'Indonesia']);
        CountryModel::create ([ 'code' =>  'IR', 'name' => 'Iran (Islamic Republic of)']);
        CountryModel::create ([ 'code' =>  'IQ', 'name' => 'Iraq']);
        CountryModel::create ([ 'code' =>  'IE', 'name' => 'Ireland']);
        CountryModel::create ([ 'code' =>  'IL', 'name' => 'Israel']);
        CountryModel::create ([ 'code' =>  'IT', 'name' => 'Italy']);
        CountryModel::create ([ 'code' =>  'CI', 'name' => 'Ivory Coast']);
        CountryModel::create ([ 'code' =>  'JE', 'name' => 'Jersey']);
        CountryModel::create ([ 'code' =>  'JM', 'name' => 'Jamaica']);
        CountryModel::create ([ 'code' =>  'JP', 'name' => 'Japan']);
        CountryModel::create ([ 'code' =>  'JO', 'name' => 'Jordan']);
        CountryModel::create ([ 'code' =>  'KZ', 'name' => 'Kazakhstan']);
        CountryModel::create ([ 'code' =>  'KE', 'name' => 'Kenya']);
        CountryModel::create ([ 'code' =>  'KI', 'name' => 'Kiribati']);
        CountryModel::create ([ 'code' =>  'KP', 'name' => 'Korea, Democratic People\'s Republic of']);
        CountryModel::create ([ 'code' =>  'KR', 'name' => 'Korea, Republic of']);
        CountryModel::create ([ 'code' =>  'XK', 'name' => 'Kosovo']);
        CountryModel::create ([ 'code' =>  'KW', 'name' => 'Kuwait']);
        CountryModel::create ([ 'code' =>  'KG', 'name' => 'Kyrgyzstan']);
        CountryModel::create ([ 'code' =>  'LA', 'name' => 'Lao People\'s Democratic Republic']);
        CountryModel::create ([ 'code' =>  'LV', 'name' => 'Latvia']);
        CountryModel::create ([ 'code' =>  'LB', 'name' => 'Lebanon']);
        CountryModel::create ([ 'code' =>  'LS', 'name' => 'Lesotho']);
        CountryModel::create ([ 'code' =>  'LR', 'name' => 'Liberia']);
        CountryModel::create ([ 'code' =>  'LY', 'name' => 'Libyan Arab Jamahiriya']);
        CountryModel::create ([ 'code' =>  'LI', 'name' => 'Liechtenstein']);
        CountryModel::create ([ 'code' =>  'LT', 'name' => 'Lithuania']);
        CountryModel::create ([ 'code' =>  'LU', 'name' => 'Luxembourg']);
        CountryModel::create ([ 'code' =>  'MO', 'name' => 'Macau']);
        CountryModel::create ([ 'code' =>  'MK', 'name' => 'Macedonia']);
        CountryModel::create ([ 'code' =>  'MG', 'name' => 'Madagascar']);
        CountryModel::create ([ 'code' =>  'MW', 'name' => 'Malawi']);
        CountryModel::create ([ 'code' =>  'MY', 'name' => 'Malaysia']);
        CountryModel::create ([ 'code' =>  'MV', 'name' => 'Maldives']);
        CountryModel::create ([ 'code' =>  'ML', 'name' => 'Mali']);
        CountryModel::create ([ 'code' =>  'MT', 'name' => 'Malta']);
        CountryModel::create ([ 'code' =>  'MH', 'name' => 'Marshall Islands']);
        CountryModel::create ([ 'code' =>  'MQ', 'name' => 'Martinique']);
        CountryModel::create ([ 'code' =>  'MR', 'name' => 'Mauritania']);
        CountryModel::create ([ 'code' =>  'MU', 'name' => 'Mauritius']);
        CountryModel::create ([ 'code' =>  'TY', 'name' => 'Mayotte']);
        CountryModel::create ([ 'code' =>  'MX', 'name' => 'Mexico']);
        CountryModel::create ([ 'code' =>  'FM', 'name' => 'Micronesia, Federated States of']);
        CountryModel::create ([ 'code' =>  'MD', 'name' => 'Moldova, Republic of']);
        CountryModel::create ([ 'code' =>  'MC', 'name' => 'Monaco']);
        CountryModel::create ([ 'code' =>  'MN', 'name' => 'Mongolia']);
        CountryModel::create ([ 'code' =>  'ME', 'name' => 'Montenegro']);
        CountryModel::create ([ 'code' =>  'MS', 'name' => 'Montserrat']);
        CountryModel::create ([ 'code' =>  'MA', 'name' => 'Morocco']);
        CountryModel::create ([ 'code' =>  'MZ', 'name' => 'Mozambique']);
        CountryModel::create ([ 'code' =>  'MM', 'name' => 'Myanmar']);
        CountryModel::create ([ 'code' =>  'NA', 'name' => 'Namibia']);
        CountryModel::create ([ 'code' =>  'NR', 'name' => 'Nauru']);
        CountryModel::create ([ 'code' =>  'NP', 'name' => 'Nepal']);
        CountryModel::create ([ 'code' =>  'NL', 'name' => 'Netherlands']);
        CountryModel::create ([ 'code' =>  'AN', 'name' => 'Netherlands Antilles']);
        CountryModel::create ([ 'code' =>  'NC', 'name' => 'New Caledonia']);
        CountryModel::create ([ 'code' =>  'NZ', 'name' => 'New Zealand']);
        CountryModel::create ([ 'code' =>  'NI', 'name' => 'Nicaragua']);
        CountryModel::create ([ 'code' =>  'NE', 'name' => 'Niger']);
        CountryModel::create ([ 'code' =>  'NG', 'name' => 'Nigeria']);
        CountryModel::create ([ 'code' =>  'NU', 'name' => 'Niue']);
        CountryModel::create ([ 'code' =>  'NF', 'name' => 'Norfolk Island']);
        CountryModel::create ([ 'code' =>  'MP', 'name' => 'Northern Mariana Islands']);
        CountryModel::create ([ 'code' =>  'NO', 'name' => 'Norway']);
        CountryModel::create ([ 'code' =>  'OM', 'name' => 'Oman']);
        CountryModel::create ([ 'code' =>  'PK', 'name' => 'Pakistan']);
        CountryModel::create ([ 'code' =>  'PW', 'name' => 'Palau']);
        CountryModel::create ([ 'code' =>  'PS', 'name' => 'Palestine']);
        CountryModel::create ([ 'code' =>  'PA', 'name' => 'Panama']);
        CountryModel::create ([ 'code' =>  'PG', 'name' => 'Papua New Guinea']);
        CountryModel::create ([ 'code' =>  'PY', 'name' => 'Paraguay']);
        CountryModel::create ([ 'code' =>  'PE', 'name' => 'Peru']);
        CountryModel::create ([ 'code' =>  'PH', 'name' => 'Philippines']);
        CountryModel::create ([ 'code' =>  'PN', 'name' => 'Pitcairn']);
        CountryModel::create ([ 'code' =>  'PL', 'name' => 'Poland']);
        CountryModel::create ([ 'code' =>  'PT', 'name' => 'Portugal']);
        CountryModel::create ([ 'code' =>  'PR', 'name' => 'Puerto Rico']);
        CountryModel::create ([ 'code' =>  'QA', 'name' => 'Qatar']);
        CountryModel::create ([ 'code' =>  'RE', 'name' => 'Reunion']);
        CountryModel::create ([ 'code' =>  'RO', 'name' => 'Romania']);
        CountryModel::create ([ 'code' =>  'RU', 'name' => 'Russian Federation']);
        CountryModel::create ([ 'code' =>  'RW', 'name' => 'Rwanda']);
        CountryModel::create ([ 'code' =>  'KN', 'name' => 'Saint Kitts and Nevis']);
        CountryModel::create ([ 'code' =>  'LC', 'name' => 'Saint Lucia']);
        CountryModel::create ([ 'code' =>  'VC', 'name' => 'Saint Vincent and the Grenadines']);
        CountryModel::create ([ 'code' =>  'WS', 'name' => 'Samoa']);
        CountryModel::create ([ 'code' =>  'SM', 'name' => 'San Marino']);
        CountryModel::create ([ 'code' =>  'ST', 'name' => 'Sao Tome and Principe']);
        CountryModel::create ([ 'code' =>  'SA', 'name' => 'Saudi Arabia']);
        CountryModel::create ([ 'code' =>  'SN', 'name' => 'Senegal']);
        CountryModel::create ([ 'code' =>  'RS', 'name' => 'Serbia']);
        CountryModel::create ([ 'code' =>  'SC', 'name' => 'Seychelles']);
        CountryModel::create ([ 'code' =>  'SL', 'name' => 'Sierra Leone']);
        CountryModel::create ([ 'code' =>  'SG', 'name' => 'Singapore']);
        CountryModel::create ([ 'code' =>  'SK', 'name' => 'Slovakia']);
        CountryModel::create ([ 'code' =>  'SI', 'name' => 'Slovenia']);
        CountryModel::create ([ 'code' =>  'SB', 'name' => 'Solomon Islands']);
        CountryModel::create ([ 'code' =>  'SO', 'name' => 'Somalia']);
        CountryModel::create ([ 'code' =>  'ZA', 'name' => 'South Africa']);
        CountryModel::create ([ 'code' =>  'GS', 'name' => 'South Georgia South Sandwich Islands']);
        CountryModel::create ([ 'code' =>  'ES', 'name' => 'Spain']);
        CountryModel::create ([ 'code' =>  'LK', 'name' => 'Sri Lanka']);
        CountryModel::create ([ 'code' =>  'SH', 'name' => 'St. Helena']);
        CountryModel::create ([ 'code' =>  'PM', 'name' => 'St. Pierre and Miquelon']);
        CountryModel::create ([ 'code' =>  'SD', 'name' => 'Sudan']);
        CountryModel::create ([ 'code' =>  'SR', 'name' => 'Suriname']);
        CountryModel::create ([ 'code' =>  'SJ', 'name' => 'Svalbard and Jan Mayen Islands']);
        CountryModel::create ([ 'code' =>  'SZ', 'name' => 'Swaziland']);
        CountryModel::create ([ 'code' =>  'SE', 'name' => 'Sweden']);
        CountryModel::create ([ 'code' =>  'CH', 'name' => 'Switzerland']);
        CountryModel::create ([ 'code' =>  'SY', 'name' => 'Syrian Arab Republic']);
        CountryModel::create ([ 'code' =>  'TW', 'name' => 'Taiwan']);
        CountryModel::create ([ 'code' =>  'TJ', 'name' => 'Tajikistan']);
        CountryModel::create ([ 'code' =>  'TZ', 'name' => 'Tanzania, United Republic of']);
        CountryModel::create ([ 'code' =>  'TH', 'name' => 'Thailand']);
        CountryModel::create ([ 'code' =>  'TG', 'name' => 'Togo']);
        CountryModel::create ([ 'code' =>  'TK', 'name' => 'Tokelau']);
        CountryModel::create ([ 'code' =>  'TO', 'name' => 'Tonga']);
        CountryModel::create ([ 'code' =>  'TT', 'name' => 'Trinidad and Tobago']);
        CountryModel::create ([ 'code' =>  'TN', 'name' => 'Tunisia']);
        CountryModel::create ([ 'code' =>  'TR', 'name' => 'Turkey']);
        CountryModel::create ([ 'code' =>  'TM', 'name' => 'Turkmenistan']);
        CountryModel::create ([ 'code' =>  'TC', 'name' => 'Turks and Caicos Islands']);
        CountryModel::create ([ 'code' =>  'TV', 'name' => 'Tuvalu']);
        CountryModel::create ([ 'code' =>  'UG', 'name' => 'Uganda']);
        CountryModel::create ([ 'code' =>  'UA', 'name' => 'Ukraine']);
        CountryModel::create ([ 'code' =>  'AE', 'name' => 'United Arab Emirates']);
        CountryModel::create ([ 'code' =>  'GB', 'name' => 'United Kingdom']);
        CountryModel::create ([ 'code' =>  'US', 'name' => 'United States']);
        CountryModel::create ([ 'code' =>  'UM', 'name' => 'United States minor outlying islands']);
        CountryModel::create ([ 'code' =>  'UY', 'name' => 'Uruguay']);
        CountryModel::create ([ 'code' =>  'UZ', 'name' => 'Uzbekistan']);
        CountryModel::create ([ 'code' =>  'VU', 'name' => 'Vanuatu']);
        CountryModel::create ([ 'code' =>  'VA', 'name' => 'Vatican City State']);
        CountryModel::create ([ 'code' =>  'VE', 'name' => 'Venezuela']);
        CountryModel::create ([ 'code' =>  'VN', 'name' => 'Vietnam']);
        CountryModel::create ([ 'code' =>  'VG', 'name' => 'Virgin Islands (British)']);
        CountryModel::create ([ 'code' =>  'VI', 'name' => 'Virgin Islands (U.S.)']);
        CountryModel::create ([ 'code' =>  'WF', 'name' => 'Wallis and Futuna Islands']);
        CountryModel::create ([ 'code' =>  'EH', 'name' => 'Western Sahara']);
        CountryModel::create ([ 'code' =>  'YE', 'name' => 'Yemen']);
        CountryModel::create ([ 'code' =>  'YU', 'name' => 'Yugoslavia']);
        CountryModel::create ([ 'code' =>  'ZR', 'name' => 'Zaire']);
        CountryModel::create ([ 'code' =>  'ZM', 'name' => 'Zambia']);
        CountryModel::create ([ 'code' =>  'ZW', 'name' => 'Zimbabwe']);
        
    }
}
